version: '3'

services:
  postgres:
    image: postgres:9.5
    env_file:
      - .dbconfig
    expose:
      - 5432
  app:
    build: .
    command: python3 main.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres